spring:
  mvc:
#    static-path-pattern: /res/**
  web:
    resources:
      static-locations: [classpath:/haha/]
      add-mappings: true
      cache:
        period: 11000
    hiddenmethod:
      filter:
        enabled: true
server:
  servlet:
    context-path: /world #所有的访问都必须以/world开始
